dist: xenial

language: clojure

before_install:
  - mariadb -e 'CREATE DATABASE g2_test;'
  - mariadb -e 'CREATE USER \'g2_user\'@\'localhost\' IDENTIFIED BY \'local-pass\';'
  - mariadb -e 'FLUSH PRIVILEGES;'
  - cp test-config_template.edn test-config.edn

script: lein test

jdk:
  - openjdk8
addons:
  mariadb: '10.0'
branches:
  only:
    - master
    - ci
# notifications:
#   slack:
#     secure:
