version: "3"
services:
  backend:
    build:
     context: . # Use the dockerfile in this repo
     dockerfile: Dockerfile
    ports:
      - "3333:3000"
    environment:
      DATABASE_URL: mysql://localhost:3306/g2_dev?user=g2_dev_user&password="0%19IG<EKR.*>%~ey<OoKOB_#"&serverTimezone=UTC
    command: >
      sh -c "lein run migrate &&
             lein run"
