version: '3.7'

services:
  backend:
    container_name: g2-backend_server
    build:
     context: . # Use the dockerfile in this repo
     dockerfile: Dockerfile
    networks:
      - base
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "mysql://db:3306/g2_dev?user=g2_user&password=local-pass&serverTimezone=UTC"
      GITHUB_PERSONAL_ACCESS_TOKEN: "af2aa061c70d1c029b1f5001c806392b4ddcf4ab"
    entrypoint: [ "sh", "stag-entrypoint.sh" ]
  db:
    container_name: g2-backend_db
    image: mariadb:10.5-focal
    volumes:
      - database:/var/lib/mysql
    networks:
      - base
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_DATABASE: g2_dev
      MYSQL_USER: g2_user
      MYSQL_PASSWORD: local-pass

networks:
  base:

volumes:
  database:
